-- Наймолодший працівник
SELECT 'YOUNGEST' AS TYPE, NAME, BIRTHDAY
FROM worker
ORDER BY BIRTHDAY ASC
LIMIT 1;

-- Найстарший працівник
UNION

SELECT 'ELDEST' AS TYPE, NAME, BIRTHDAY
FROM worker
ORDER BY BIRTHDAY DESC
LIMIT 1;